version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  gemini_service:
    build: ./Gemini_service
    container_name: gemini_service
    ports:
      - "8002:8002"
    env_file:
      - ./Gemini_service/.env
    depends_on:
      - mongodb

volumes:
  mongo-data:
