runtime: python39
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

instance_class: F2  # Optional: adjust to F1/B1 for cost saving

env_variables:
  GEMINI_VERTEX_API_KEY: "AIzaSyBqe3TLAgIVxuuXOpo5wvVxRcBgjrZbgFM"
  MONGODB_URI: "mongodb+srv://ram0327mj:Asdflkj@manoj.o6m0o.mongodb.net/?retryWrites=true&w=majority&appName=Manoj"
