runtime: python39  
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

instance_class: F2  # Optional: Set instance type

env_variables:
  GEMINI_VERTEX_API_KEY: "your_actual_key"
  GOOGLE_APPLICATION_CREDENTIALS: "gcp-key.json.json"
  OCR_APPLICATION_CREDENTIALS: "ocr-key.json.json"

handlers:
  - url: /.*
    script: auto
